"""docs/pipeline/status.md generation: a table per stage, open promotion proposals, flags, the last
20 events. rendered from the database only (the file is regenerated by `pipeline.py report`)."""
from __future__ import annotations

import datetime as dt
import json
import os
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
STATUS_MD = ROOT / "docs" / "pipeline" / "status.md"

LANE = ["proposed", "backtesting", "backtest_passed", "shadow", "shadow_passed", "promotion_proposed",
        "promoted", "backtest_failed", "shadow_failed", "rejected", "withdrawn"]
ACTIVE = {"proposed", "backtesting", "backtest_passed", "shadow", "shadow_passed", "promotion_proposed"}


def _age(ts: str | None, now: dt.datetime) -> str:
    if not ts:
        return "—"
    t = dt.datetime.fromisoformat(ts.replace("Z", "+00:00"))
    d = now - t
    if d.days >= 1:
        return f"{d.days} d"
    h = d.seconds // 3600
    return f"{h} h" if h else f"{d.seconds // 60} m"


def _num(x, fmt="{:+.0f}"):
    return "—" if x is None else fmt.format(x)


def _bt_cell(c: dict) -> str:
    r = c.get("backtest_result") or {}
    m = r.get("metrics")
    if not m:
        if r.get("blocked"):
            return f"blocked: {r['blocked']}"
        return "—"
    years = " ".join(f"{y[2:]}:{m['years'][y]['pnl']:+.0f}" for y in sorted(m.get("years", {})))
    gate = r.get("gate_result") or {}
    verdict = ("**pass**" if gate.get("pass") else "fail: " + ", ".join(c2["name"] for c2 in gate.get("checks", []) if not c2["ok"])) if gate else "—"
    base = r.get("baseline") or {}
    bm = base.get("metrics")
    bcell = f" · base {base.get('tag')}: {bm['pnl']:+.0f} / {bm['n']} / PF {bm['pf']:.2f}" if bm else ""
    mg = m.get("marginal")
    addcell = ""
    if mg:
        a = mg["added"]
        addcell = f" · added {a['pnl']:+.0f} / {a['n']} / PF {a['pf']:.2f} (worst yr {a['worst_year_pnl']:+.0f}, worst day {a['worst_day']:+.0f})"
    return f"{m['pnl']:+.0f} / {m['n']} / PF {m['pf']:.2f} · {years} · {verdict}{bcell}{addcell}"


def _shadow_cell(c: dict) -> str:
    s = c.get("shadow_status") or {}
    r = c.get("shadow_result") or {}
    bits = []
    if s:
        bits.append(f"{s.get('sessions', 0)} sessions / {s.get('trades', 0)} trades / {_num(s.get('pnl'))}")
        if s.get("due_reason"):
            bits.append(s["due_reason"])
    if r.get("flag"):
        bits.append(f"**flag: {r['flag']}**")
    if r.get("verdict"):
        bits.append(f"verdict: {r['verdict']}")
    return " · ".join(bits) or "—"


def render(cands: list[dict], events: list[dict], baseline: dict | None, meta: dict) -> str:
    now = dt.datetime.now(dt.timezone.utc)
    out = []
    out.append("# research pipeline — status")
    out.append("")
    out.append(f"generated {now.strftime('%Y-%m-%d %H:%M UTC')} by `scripts/pipeline/pipeline.py report`. "
               "do not edit: regenerated nightly. lane: proposed → backtesting → backtest_passed → shadow → "
               "shadow_passed → promotion_proposed → promoted (human). failures: backtest_failed / shadow_failed "
               "(180 d cooldown), withdrawn (human).")
    out.append("")
    out.append("- gate sweeps run at the research sizing (`--sizing-fraction 0.36 --max-position-pct 0.36 --cross-index SPY`, "
               "IEX cache, 3 bps + $0.005); the per-year floor (no year < −300) is stated at 36 %. live and shadow books size at the blob's fraction; parity replays use no sizing override.")
    sw = meta.get("shadow_books_enabled")
    out.append(f"- shadow-book creation: **{'enabled' if sw else 'disabled'}** (`PIPELINE_SHADOW_BOOKS={'1' if sw else '0'}`; "
               "while disabled `advance` only prints the books it would create).")
    if baseline:
        yrs = " ".join(f"{y[2:]}:{baseline['years'][y]['pnl']:+.0f}" for y in sorted(baseline["years"]))
        out.append(f"- baseline `{baseline['tag']}` (promoted row on its own tickers): {baseline['pnl']:+.0f} / {baseline['n']} trades / PF {baseline['pf']:.2f} · {yrs}")
    out.append("")

    proposals = [c for c in cands if c["stage"] == "promotion_proposed"]
    out.append("## promotion proposals (open)")
    out.append("")
    if not proposals:
        out.append("none.")
    for c in proposals:
        block = ((c.get("shadow_result") or {}).get("proposal_md")) or f"promote candidate `{c['name']}` → config row {c.get('proposed_config_version_id')}"
        out.append(block.rstrip())
        out.append("")
    out.append("")

    flags = [c for c in cands if c["stage"] in ACTIVE and ((c.get("shadow_result") or {}).get("flag") or (c.get("backtest_result") or {}).get("blocked"))]
    out.append("## flags (plumbing, not verdicts)")
    out.append("")
    if not flags:
        out.append("none.")
    for c in flags:
        f = (c.get("shadow_result") or {}).get("flag") or (c.get("backtest_result") or {}).get("blocked")
        detail = (c.get("shadow_result") or {}).get("flag_detail") or (c.get("backtest_result") or {}).get("blocked_detail") or ""
        out.append(f"- `{c['name']}` (#{c['id']}, {c['stage']}): **{f}** {detail}".rstrip())
    out.append("")

    out.append("## candidates by stage")
    out.append("")
    by_stage = {s: [c for c in cands if c["stage"] == s] for s in LANE}
    for s in LANE:
        rows = by_stage[s]
        if not rows and s not in ACTIVE:
            continue
        out.append(f"### {s} ({len(rows)})")
        out.append("")
        if not rows:
            out.append("none.")
            out.append("")
            continue
        if s in ("shadow", "shadow_passed", "promotion_proposed", "shadow_failed", "promoted"):
            out.append("| id | name | kind | gate | book | since | trial | backtest |")
            out.append("|---:|---|---|---|---|---|---|---|")
            for c in rows:
                out.append(f"| {c['id']} | `{c['name']}` | {c['kind']} | {c['gate']} | {c.get('shadow_book') or '—'} | {_age(c.get('updated_at'), now)} | {_shadow_cell(c)} | {_bt_cell(c)} |")
        else:
            out.append("| id | name | kind | gate | tickers | since | backtest (5y P&L / trades / PF · per year · gate) |")
            out.append("|---:|---|---|---|---|---|---|")
            for c in rows:
                t = ",".join(c["tickers"]) if c.get("tickers") else "base"
                extra = f" · cooldown to {c['cooldown_until']}" if c.get("cooldown_until") and s in ("backtest_failed", "shadow_failed") else ""
                out.append(f"| {c['id']} | `{c['name']}` | {c['kind']} | {c['gate']} | {t} | {_age(c.get('updated_at'), now)} | {_bt_cell(c)}{extra} |")
        out.append("")

    out.append("## last 20 events")
    out.append("")
    out.append("| when (UTC) | candidate | transition | actor | detail |")
    out.append("|---|---|---|---|---|")
    for e in events[:20]:
        d = e.get("detail") or {}
        summary = d.get("event") or d.get("reason") or ""
        keys = [k for k in ("config_version_id", "tag", "verdict", "book", "pass", "why") if k in d]
        if keys:
            summary += " " + " ".join(f"{k}={d[k]}" for k in keys)
        ts = e["ts"][:16].replace("T", " ")
        tr = f"{e.get('from_stage') or '∅'} → {e['to_stage']}"
        out.append(f"| {ts} | `{e['name']}` | {tr} | {e['actor']} | {summary.strip()[:140]} |")
    out.append("")
    return "\n".join(out)


def write(md: str, path: Path = STATUS_MD) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(".md.tmp")
    tmp.write_text(md)
    os.replace(tmp, path)
    return path
