"""rankings from s1/s2/s3/s5 csv -> tables.md + top lists (json) for pairs.py. python stdlib only."""
import csv, os, json, statistics
SCREEN = os.path.dirname(os.path.abspath(__file__))
YEARS = [2022, 2023, 2024, 2025, 2026]
MIN_EPS = 30
meta = json.load(open(os.path.join(SCREEN, 'meta.json')))
base = {int(k): v for k, v in meta['base'].items()}

def rows(name):
    with open(os.path.join(SCREEN, name)) as f:
        return list(csv.DictReader(f))
def f(x):
    return None if x in ('', None) else float(x)
def p(x, d=3):
    return '' if x is None else f'{100 * x:+.{d}f}'
def by_feature(rs, key='feature'):
    out = {}
    for r in rs: out.setdefault(r[key], {})[int(r['year'])] = r
    return out

# ---------------- screen 1
s1 = by_feature(rows('s1_feature_alone.csv'))
sum1 = []
for name, yrs in s1.items():
    grp = yrs[YEARS[0]]['group']
    means = {y: f(yrs[y]['mean']) for y in YEARS}; eps = {y: int(yrs[y]['eps']) for y in YEARS}; bars = {y: int(yrs[y]['bars']) for y in YEARS}
    ep_means = {y: f(yrs[y]['ep_mean']) for y in YEARS}
    beat = sum(1 for y in YEARS if means[y] is not None and means[y] > base[y]['mean'])
    tb = sum(bars.values())
    pooled = sum(means[y] * bars[y] for y in YEARS if means[y] is not None) / tb if tb else None
    te = sum(eps.values())
    pooled_ep = sum(ep_means[y] * eps[y] for y in YEARS if ep_means[y] is not None) / te if te else None
    hit = sum(f(yrs[y]['hit']) * bars[y] for y in YEARS if yrs[y]['hit']) / tb if tb else None
    top5 = sum(f(yrs[y]['top5']) * bars[y] for y in YEARS if yrs[y]['top5']) / tb if tb else None
    sum1.append(dict(feature=name, group=grp, beat=beat, min_eps=min(eps.values()), eps_yr=te / 5, pooled=pooled, pooled_ep=pooled_ep, hit=hit, top5=top5,
                     means=means, eps=eps, candidate=(beat >= 4 and min(eps.values()) >= MIN_EPS and pooled is not None and pooled > 0),
                     pooled_pos=(pooled is not None and pooled > 0)))
sum1.sort(key=lambda r: (-r['beat'], -(r['pooled'] or -9)))

# ---------------- screen 2
s2 = by_feature(rows('s2_conditional.csv'))
sum2 = []
for name, yrs in s2.items():
    grp = yrs[YEARS[0]]['group']
    for mode in ('req', 'excl'):
        means = {y: f(yrs[y][f'{mode}_mean']) for y in YEARS}; eps = {y: int(yrs[y][f'{mode}_eps']) for y in YEARS}
        keep = {y: f(yrs[y][f'{mode}_keep']) for y in YEARS}
        wm = {y: f(yrs[y]['win_mean']) for y in YEARS}; weps = {y: int(yrs[y]['win_eps']) for y in YEARS}
        raised = sum(1 for y in YEARS if means[y] is not None and means[y] > wm[y])
        te = sum(eps.values()); tw = sum(weps.values())
        pooled = sum(means[y] * int(yrs[y][f'{mode}_bars']) for y in YEARS if means[y] is not None) / max(1, sum(int(yrs[y][f'{mode}_bars']) for y in YEARS))
        pooled_ep = sum(f(yrs[y][f'{mode}_ep_mean']) * eps[y] for y in YEARS if yrs[y][f'{mode}_ep_mean']) / te if te else None
        win_pooled = sum(wm[y] * int(yrs[y]['win_bars']) for y in YEARS) / sum(int(yrs[y]['win_bars']) for y in YEARS)
        sum2.append(dict(feature=name, group=grp, mode=mode, raised=raised, keep=te / tw, min_eps=min(eps.values()), eps=eps, means=means, wmeans=wm,
                         pooled=pooled, pooled_ep=pooled_ep, win_pooled=win_pooled, candidate=(raised >= 4 and te / tw >= 0.40)))
sum2.sort(key=lambda r: (-r['raised'], -r['keep']))
win_eps = {y: int(next(iter(s2.values()))[y]['win_eps']) for y in YEARS}
win_means = {y: f(next(iter(s2.values()))[y]['win_mean']) for y in YEARS}

# ---------------- screen 3
s3 = {}
for r in rows('s3_sim.csv'):
    s3.setdefault((r['trigger'], r['mode']), {})[int(r['year'])] = r
sum3 = []
for (name, mode), yrs in s3.items():
    pnl = {y: f(yrs[y]['pnl']) for y in YEARS}; tr = {y: int(yrs[y]['trades']) for y in YEARS}; pf = {y: f(yrs[y]['pf']) for y in YEARS}
    lab = {y: f(yrs[y]['lab_pnl']) for y in YEARS}; ltr = {y: int(yrs[y]['lab_trades']) for y in YEARS}
    tot = sum(pnl.values()); ntr = sum(tr.values())
    # pooled PF from per-year gross: reconstruct gw/gl from pnl and pf: gw - gl = pnl, gw/gl = pf -> gl = pnl/(pf-1)
    gw = gl = 0.0
    for y in YEARS:
        if pf[y] is None or tr[y] == 0: continue
        if pf[y] == float('inf'): gw += pnl[y]; continue
        g_l = pnl[y] / (pf[y] - 1) if pf[y] != 1 else 0
        gl += g_l; gw += g_l * pf[y]
    sum3.append(dict(trigger=name, mode=mode, group=yrs[YEARS[0]]['group'], pnl=pnl, trades=tr, pf=pf, total=tot, ntrades=ntr,
                     pos_years=sum(1 for y in YEARS if pnl[y] > 0), pooled_pf=(gw / gl if gl > 0 else None), lab=lab, lab_total=sum(lab.values()), lab_trades=sum(ltr.values())))
sum3.sort(key=lambda r: (-r['pos_years'], -r['total']))

# ---------------- screen 5
s5 = {}
for r in rows('s5_patterns.csv'):
    s5.setdefault(r['pattern'], {})[int(r['year'])] = r

# ---------------- markdown
L = []
L.append('# screen tables (auto-generated by summarize.py)\n')
L.append('## base rates (all 09:30-11:29 bars, hypothetical short, label exit stack)\n')
L.append('| year | bars | mean opp_pnl % | median % | hit | top-5% threshold % | split days nulled |')
L.append('|---|---|---|---|---|---|---|')
for y in YEARS:
    b = base[y]
    L.append(f"| {y} | {b['bars']} | {p(b['mean'])} | {p(b['median'])} | {100*b['hit']:.1f}% | {p(b['top_thr'],2)} | {', '.join('/'.join(x) for x in b['split_days'])} |")
L.append('')
L.append('## screen 1 — feature alone (per-year mean opp_pnl %, bar-level; base in header; eps = episodes)\n')
hdr = '| feature | group | yrs>base | min eps/yr | ' + ' | '.join(f'{y} ({p(base[y]["mean"],2)})' for y in YEARS) + ' | pooled mean | pooled ep-mean | hit | top5 share | cand |'
L.append(hdr); L.append('|' + '---|' * (hdr.count('|') - 1))
for r in sum1:
    cells = ' | '.join(f"{p(r['means'][y],2)} / {r['eps'][y]}" for y in YEARS)
    L.append(f"| {r['feature']} | {r['group']} | {r['beat']} | {r['min_eps']} | {cells} | {p(r['pooled'])} | {p(r['pooled_ep'])} | {100*(r['hit'] or 0):.1f}% | {100*(r['top5'] or 0):.1f}% | {'YES' if r['candidate'] else ''} |")
L.append('')
L.append('## screen 2 — as a condition on the v16 windows (require / exclude). window bars: mean per year in header\n')
L.append('window episodes per year: ' + ', '.join(f'{y}: {win_eps[y]} (mean {p(win_means[y],2)})' for y in YEARS) + '\n')
hdr = '| feature | mode | yrs raised | keep (eps) | min eps | ' + ' | '.join(str(y) for y in YEARS) + ' | pooled mean (win) | pooled ep-mean | cand |'
L.append(hdr); L.append('|' + '---|' * (hdr.count('|') - 1))
for r in sum2:
    cells = ' | '.join(f"{p(r['means'][y],2)} / {r['eps'][y]}" for y in YEARS)
    L.append(f"| {r['feature']} | {r['mode']} | {r['raised']} | {100*r['keep']:.0f}% | {r['min_eps']} | {cells} | {p(r['pooled'])} ({p(r['win_pooled'])}) | {p(r['pooled_ep'])} | {'YES' if r['candidate'] else ''} |")
L.append('')
L.append('## screen 3 — simulation, $3,600 per position, honest costs, v16 exit stack (label-exit total in last col)\n')
hdr = '| trigger | mode | pos yrs | ' + ' | '.join(str(y) for y in YEARS) + ' | 5y P&L | trades | pooled PF | label-exit 5y P&L / trades |'
L.append(hdr); L.append('|' + '---|' * (hdr.count('|') - 1))
for r in sum3:
    cells = ' | '.join(f"{r['pnl'][y]:+,.0f} ({r['trades'][y]}, PF {r['pf'][y]:.2f})" if r['pf'][y] is not None else '-' for y in YEARS)
    L.append(f"| {r['trigger']} | {r['mode']} | {r['pos_years']} | {cells} | {r['total']:+,.0f} | {r['ntrades']} | {r['pooled_pf'] if r['pooled_pf'] is None else f'{r['pooled_pf']:.2f}'} | {r['lab_total']:+,.0f} / {r['lab_trades']} |")
L.append('')
L.append('## screen 5 — bearish candle patterns: fired with s5m <= -0.40 vs fired with s5m > 0 (mean opp % / episodes)\n')
hdr = '| pattern | ' + ' | '.join(f'{y} s5<=-.4 | {y} s5>0' for y in YEARS) + ' | pooled s5<=-.4 | pooled s5>0 | pooled s1m>0 | pooled on-window |'
L.append(hdr); L.append('|' + '---|' * (hdr.count('|') - 1))
for pat, yrs in s5.items():
    def pooled(prefix):
        tb = sum(int(yrs[y][f'{prefix}_bars']) for y in YEARS) if f'{prefix}_bars' in yrs[YEARS[0]] else sum(int(yrs[y][f'{prefix}_eps']) for y in YEARS)
        if tb == 0: return None, 0
        key_n = f'{prefix}_bars' if f'{prefix}_bars' in yrs[YEARS[0]] else f'{prefix}_eps'
        return sum(f(yrs[y][f'{prefix}_mean']) * int(yrs[y][key_n]) for y in YEARS if yrs[y][f'{prefix}_mean']) / tb, sum(int(yrs[y][f'{prefix}_eps']) for y in YEARS)
    cells = ' | '.join(f"{p(f(yrs[y]['s5le40_mean']),2)} / {yrs[y]['s5le40_eps']} | {p(f(yrs[y]['s5gt0_mean']),2)} / {yrs[y]['s5gt0_eps']}" for y in YEARS)
    a = pooled('s5le40'); b = pooled('s5gt0'); c = pooled('s1gt0'); w = pooled('win')
    L.append(f"| {pat} | {cells} | {p(a[0])} / {a[1]} | {p(b[0])} / {b[1]} | {p(c[0])} / {c[1]} | {p(w[0])} / {w[1]} |")
open(os.path.join(SCREEN, 'tables.md'), 'w').write('\n'.join(L) + '\n')

top = dict(s1=[r['feature'] for r in sum1 if r['candidate'] and r['group'] != 'ref'][:12],
           s1_all_ranked=[(r['feature'], r['beat'], r['min_eps'], r['pooled']) for r in sum1 if r['group'] != 'ref'][:25],
           s2=[(r['feature'], r['mode']) for r in sum2 if r['candidate']])
json.dump(top, open(os.path.join(SCREEN, 'top.json'), 'w'), indent=1)
print('screen-1 candidates:', top['s1'])
print('screen-2 candidates:', top['s2'])
print('wrote tables.md, top.json')
